version: '2'

services:
  slack-gateway:
    image: outofcoffee/slack-gateway
    build: ./distro
    ports:
      - "8080:8080"
      # Java debug port
      - "8000:8000"
    environment:
      - SLACK_USER_TOKEN
      - SLACK_CHANNEL_MEMBERS
      - JAVA_OPTS
